const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",

  CHECK_AUTH: "CHECK_AUTH",

  SET_TOKEN: "SET_TOKEN",
  SET_MESSAGE: "SET_MESSAGE",
  SET_POP_UP: "SET_POP_UP",
  SET_LOADING: "SET_LOADING",
  SET_AUTHENTICATING: "SET_AUTHENTICATING",

  SIGN_IN_BY_TOKEN_START: "SIGN_IN_BY_TOKEN_START",
  SIGN_IN_BY_TOKEN_SUCCESS: "SIGN_IN_BY_TOKEN_SUCCESS",
  SIGN_IN_BY_TOKEN_FAILURE: "SIGN_IN_BY_TOKEN_FAILURE",

  RESEND_CONFIRM_EMAIL_START: "RESEND_CONFIRM_EMAIL_START",
  RESEND_CONFIRM_EMAIL_SUCCESS: "RESEND_CONFIRM_EMAIL_SUCCESS",

  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  FORGET_PASSWORD_START: "FORGET_PASSWORD_START",
  FORGET_PASSWORD_SUCCESS: "FORGET_PASSWORD_SUCCESS",

  RESET_PASSWORD: "RESET_PASSWORD",

  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
};

export default UserActionTypes;
